Repository Learning-Is-Vital-In-Development/23-18-frontend-test, pull requests merged in 2023-11, with the labels that each got.

#21 [3,4주차] 이지훈
  package.json
  src/03-menuOption/jiji-hoon96/MenuOption.test.tsx
  src/03-menuOption/jiji-hoon96/MenuOption.tsx
  src/jiji-hoon96/2주차/2주차.md
  src/jiji-hoon96/2주차/Menu.module.css
  src/jiji-hoon96/2주차/Menu.test.tsx
  src/jiji-hoon96/2주차/Menu.tsx
  src/jiji-hoon96/2주차/image.png
  src/jiji-hoon96/2주차/types.d.ts
  src/jiji-hoon96/3주차/MenuOption.module.css
  src/jiji-hoon96/3주차/MenuOption.test.tsx
  src/jiji-hoon96/3주차/MenuOption.tsx
  src/jiji-hoon96/3주차/constant.ts
  src/jiji-hoon96/3주차/mockData.ts
  src/jiji-hoon96/3주차/types.d.ts
Labels: size/L

#28 [2주차] 이하은
  package.json
  src/leehaeun0/components/MenuItem/MenuItem.test.tsx
  src/leehaeun0/components/MenuItem/MenuItem.tsx
  src/leehaeun0/components/MenuList/MenuList.test.tsx
  src/leehaeun0/components/MenuList/MenuList.tsx
  src/leehaeun0/mocks/menu.ts
  src/leehaeun0/types/menu.ts
  yarn.lock
Labels: size/XXL

#22 [5주차] 도혜원
  package-lock.json
  package.json
  src/dohye1/App.tsx
  src/dohye1/MenuItem.tsx
  src/dohye1/component/MenuItem/MenuItem.test.tsx
  src/dohye1/component/MenuItem/index.tsx
  src/dohye1/component/MenuItem/style.module.css
  src/dohye1/component/MenuList/MenuList.test.tsx
  src/dohye1/component/MenuList/index.tsx
  src/dohye1/component/MenuList/style.module.css
  src/dohye1/component/MenuOption/MenuOption.test.tsx
  src/dohye1/component/MenuOption/index.tsx
  src/dohye1/constant/index.tsx
  src/dohye1/constant/testId.ts
  src/dohye1/context/CartContext.tsx
  src/dohye1/hooks/useCart.tsx
  src/dohye1/pages/Home.tsx
  src/dohye1/pages/Store/SelectOption.test.tsx
  src/dohye1/pages/Store/SelectOption.tsx
  src/dohye1/pages/Store/StoreDetail.test.tsx
  src/dohye1/pages/Store/StoreDetail.tsx
  src/dohye1/pages/Store/StoreList.tsx
  src/dohye1/pages/Store/index.tsx
  src/dohye1/route/index.tsx
  src/dohye1/types.d.ts
  src/dohye1/utils/index.ts
  src/dohye1/utils/mock.util.ts
  src/dohye1/utils/price.util.ts
  src/dohye1/utils/test.util.tsx
Labels: size/XL

#29 coverage 워크플로우 추가
  .github/workflows/jest-coverage.yml
Labels: size/S

#26 [5주차] 정수현
  src/sasha1107/App.tsx
  src/sasha1107/__tests__/Cart.test.tsx
  src/sasha1107/__tests__/Menu.test.tsx
  src/sasha1107/__tests__/MenuList.test.tsx
  src/sasha1107/__tests__/MenuOption.test.tsx
  src/sasha1107/components/Menu/index.tsx
  src/sasha1107/components/MenuList/index.tsx
  src/sasha1107/components/MenuOption/index.tsx
  src/sasha1107/constants/cafe.json
  src/sasha1107/constants/data.json
  src/sasha1107/constants/menu.json
  src/sasha1107/hooks/index.ts
  src/sasha1107/hooks/useQueryString.ts
  src/sasha1107/pages/home/index.tsx
  src/sasha1107/pages/index.ts
  src/sasha1107/pages/option/index.tsx
  src/sasha1107/pages/result/index.tsx
  src/sasha1107/pages/store/index.tsx
  src/sasha1107/routes/index.tsx
  src/sasha1107/types/index.ts
  src/sasha1107/utils/decodeBase64.ts
  src/sasha1107/utils/encodeBase64.ts
  src/sasha1107/utils/index.ts
Labels: size/XL

#32 [3주차] 이하은
  package-lock.json
  src/leehaeun0/pages/MenuDetailPage/MenuDetailPage.test.tsx
  src/leehaeun0/pages/MenuDetailPage/MenuDetailPage.tsx
  src/leehaeun0/types/menu.ts
Labels: size/L

#30 [5주차] 박소영
  src/sso214/App.tsx
  src/sso214/Page.tsx
  src/sso214/components/Button/index.ts
  src/sso214/components/Heading/Heading.test.tsx
  src/sso214/components/Heading/Heading.tsx
  src/sso214/components/Heading/index.ts
  src/sso214/components/Layout/Layout.tsx
  src/sso214/components/Layout/index.ts
  src/sso214/components/List/List.test.tsx
  src/sso214/components/List/List.tsx
  src/sso214/components/List/index.ts
  src/sso214/components/Menu/Menu.test.tsx
  src/sso214/components/Menu/Menu.tsx
  src/sso214/components/Menu/index.ts
  src/sso214/components/Menu/types.ts
  src/sso214/components/MenuList/MenuList.test.tsx
  src/sso214/components/MenuList/MenuList.tsx
  src/sso214/components/MenuList/index.ts
  src/sso214/components/MenuOption/MenuOption.test.tsx
  src/sso214/components/MenuOption/MenuOption.tsx
  src/sso214/components/MenuOption/index.ts
  src/sso214/components/NoMatch/NoMatch.tsx
  src/sso214/components/NoMatch/index.ts
  src/sso214/components/NumberAdjuster/NumberAdjuster.test.tsx
  src/sso214/components/NumberAdjuster/NumberAdjuster.tsx
  src/sso214/components/NumberAdjuster/index.ts
  src/sso214/components/Radios/Radios.test.tsx
  src/sso214/components/Radios/Radios.tsx
  src/sso214/components/Radios/index.ts
  src/sso214/components/index.ts
  src/sso214/constant/TEST_ID.ts
  src/sso214/context/CartContext.tsx
  src/sso214/data/MENU_LIST.ts
  src/sso214/hooks/useCart.ts
  src/sso214/mock/cafe_menu.json
  src/sso214/mock/snack_menu.json
  src/sso214/pages/Home/Home.tsx
  src/sso214/pages/Home/index.ts
  src/sso214/pages/Store/Store.tsx
  src/sso214/pages/Store/StoreDetail.test.tsx
  src/sso214/pages/Store/StoreDetail.tsx
  src/sso214/pages/Store/StoreOption.test.tsx
  src/sso214/pages/Store/StoreOption.tsx
  src/sso214/pages/Store/index.ts
  src/sso214/pages/index.ts
  src/sso214/routes/index.tsx
  src/sso214/types/Model.ts
  src/sso214/utils/index.ts
  src/sso214/utils/mock.util.ts
  src/sso214/utils/test.util.tsx
Labels: size/XXL

#34 e2e 테스트 환경 구축
  .gitignore
  jest.config.ts
  package-lock.json
  package.json
  playwright.config.base.ts
  src/e2e-example/App.tsx
  src/e2e-example/e2e/example.spec.ts
  src/e2e-example/index.html
  src/e2e-example/main.tsx
  src/e2e-example/playwright.config.ts
  src/e2e-example/vite-env.d.ts
  src/e2e-example/vite.config.ts
Labels: size/L
