Repository Learning-Is-Vital-In-Development/23-18-frontend-test, pull requests merged in 2023-10, with the labels that each got.

#1 ci 테스트
  .eslintrc.json
  .github/CODEOWNERS
  .github/workflows/jest-test.yaml
  .npmrc
  .nvmrc
  package-lock.json
  package.json
Labels: size/M

#3 [1주차] 정수현
  src/01-practices/soohyun/Stack.test.tsx
  src/01-practices/soohyun/Stack.tsx
  src/01-practices/soohyun/getTriangleArea.test.ts
  src/01-practices/soohyun/getTriangleArea.ts
Labels: size/L

#4 feat : 1주차 이지훈
  src/01-practices/jiji-hoon96/1주차.md
  src/01-practices/jiji-hoon96/Stack.test.tsx
  src/01-practices/jiji-hoon96/Stack.tsx
  src/01-practices/jiji-hoon96/getTriangleArea.test.ts
  src/01-practices/jiji-hoon96/getTriangleArea.ts
Labels: size/M

#5 10월 10일 테스트 코드 실습
  src/01-practices/codyMan0/Stack.tsx
  src/01-practices/codyMan0/getTriangle.test.ts
  src/01-practices/codyMan0/getTriangle.ts
Labels: size/M

#6 :test_tube: 1회차
  src/01-practices/dohye1/Stack.test.tsx
  src/01-practices/dohye1/Stack.tsx
  src/01-practices/dohye1/index.test.ts
  src/01-practices/dohye1/index.ts
Labels: size/M

#8 Css module
  .vscode/settings.json
  jest.config.ts
  notes/week-01.md
  package-lock.json
  package.json
  src/01-practices/.gitkeep
  src/Example.module.css
  src/Example.test.tsx
  src/Example.tsx
  src/types.d.ts
  tsconfig.json
Labels: size/M

#7 feat : 1회차 실습
  src/01-practices/sso214/Stack.test.tsx
  src/01-practices/sso214/Stack.tsx
  src/01-practices/sso214/triangles.test.ts
  src/01-practices/sso214/triangles.ts
Labels: size/L

#9 :lipstick: menu item 컴포넌트 추가
  src/dohye1/MenuItem.module.css
  src/dohye1/MenuItem.tsx
  src/dohye1/types.d.ts
  src/dohye1/util.ts
Labels: size/M

#10 [2주차] 이주영
  src/01-practices/codyMan0/1주차/Stack.test.tsx
  src/01-practices/codyMan0/1주차/Stack.tsx
  src/01-practices/codyMan0/1주차/getTriangle.test.ts
  src/01-practices/codyMan0/1주차/getTriangle.ts
  src/01-practices/codyMan0/2주차/asset/img.jpeg
  src/01-practices/codyMan0/2주차/cart/Cart.module.css
  src/01-practices/codyMan0/2주차/cart/Cart.test.tsx
  src/01-practices/codyMan0/2주차/cart/Cart.tsx
  src/01-practices/codyMan0/2주차/cartItem/CartItem.test.tsx
  src/01-practices/codyMan0/2주차/cartItem/CartItem.tsx
  src/01-practices/codyMan0/2주차/type.ts
  src/01-practices/codyMan0/Stack.tsx
  src/01-practices/codyMan0/getTriangle.test.ts
  src/01-practices/codyMan0/getTriangle.ts
Labels: size/L

#11 feat : 2주차 과제
  src/sso214/Page.tsx
  src/sso214/components/Heading/Heading.tsx
  src/sso214/components/Heading/index.ts
  src/sso214/components/Heading/style.module.css
  src/sso214/components/List/List.tsx
  src/sso214/components/List/index.ts
  src/sso214/components/Menu/Menu.tsx
  src/sso214/components/Menu/index.ts
  src/sso214/components/Menu/style.module.css
  src/sso214/components/Menu/types.d.ts
  src/sso214/components/MenuList/MenuList.tsx
  src/sso214/components/MenuList/index.ts
  src/sso214/components/MenuList/style.module.css
  src/sso214/components/index.ts
Labels: size/L

#14 [2주차] 정수현
  src/soohyun/02-menu/__tests__/Menu.test.tsx
  src/soohyun/02-menu/__tests__/MenuList.test.tsx
  src/soohyun/02-menu/components/Menu.tsx
  src/soohyun/02-menu/components/MenuList.tsx
  src/soohyun/02-menu/components/index.ts
  src/soohyun/02-menu/constants/menu.json
  src/soohyun/02-menu/types/index.ts
Labels: size/L

#12 [2주차] 이지훈
  src/02-menu/jiji-hoon96/2주차.md
  src/02-menu/jiji-hoon96/Menu.module.css
  src/02-menu/jiji-hoon96/Menu.test.tsx
  src/02-menu/jiji-hoon96/Menu.tsx
  src/02-menu/jiji-hoon96/image.png
  src/02-menu/jiji-hoon96/types.d.ts
  src/03-menuOption/jiji-hoon96/MenuOption.module.css
  src/03-menuOption/jiji-hoon96/MenuOption.test.tsx
  src/03-menuOption/jiji-hoon96/MenuOption.tsx
  src/03-menuOption/jiji-hoon96/types.d.ts
Labels: size/XL

#18 :test_tube: 메뉴 리스트 컴포넌트 및 테스트 코드 추가
  package-lock.json
  package.json
  src/dohye1/MenuItem.module.css
  src/dohye1/component/MenuItem/MenuItem.test.tsx
  src/dohye1/component/MenuItem/index.tsx
  src/dohye1/component/MenuItem/style.module.css
  src/dohye1/component/MenuList/MenuList.test.tsx
  src/dohye1/component/MenuList/index.tsx
  src/dohye1/component/MenuList/style.module.css
  src/dohye1/types.d.ts
  src/dohye1/utils/index.ts
  src/dohye1/utils/mock.util.ts
  src/dohye1/utils/price.util.ts
Labels: size/L

#17 3주차
  src/01-practices/codyMan0/2주차/cart/Cart.test.tsx
  src/01-practices/codyMan0/2주차/cart/Cart.tsx
  src/01-practices/codyMan0/2주차/cartItem/CartItem.test.tsx
  src/01-practices/codyMan0/2주차/cartItem/CartItem.tsx
  src/01-practices/codyMan0/2주차/type.ts
  src/01-practices/codyMan0/3주차 /asset/3주차.jpeg
  src/01-practices/codyMan0/3주차 /constant.ts
  src/01-practices/codyMan0/3주차 /menu/MenuForm.test.tsx
  src/01-practices/codyMan0/3주차 /menu/Menuform.tsx
  src/01-practices/codyMan0/3주차 /menu/components/multiPriceOptions/MultiPriceOptions.tsx
  src/01-practices/codyMan0/3주차 /menu/components/nav/NavFooter.tsx
  src/01-practices/codyMan0/3주차 /menu/components/priceAmount/PriceAmount.tsx
  src/01-practices/codyMan0/3주차 /menu/components/singlePriceOptions/SinglePriceOption.tsx
  src/01-practices/codyMan0/3주차 /menu/components/toggler/Toggler.tsx
  src/01-practices/codyMan0/3주차 /type.ts
Labels: size/L

#16 [3주차] 이지훈
  src/03-menuOption/jiji-hoon96/MenuOption.test.tsx
  src/03-menuOption/jiji-hoon96/MenuOption.tsx
Labels: size/S

#24 폴더명 변경
  src/sasha1107/__tests__/Menu.test.tsx
  src/sasha1107/__tests__/MenuList.test.tsx
  src/sasha1107/components/Menu.tsx
  src/sasha1107/components/MenuList.tsx
  src/sasha1107/components/index.ts
  src/sasha1107/constants/menu.json
  src/sasha1107/types/index.ts
Labels: size/XS

#20 [2주차] 박소영 (테스트 코드 추가)
  src/sso214/Page.tsx
  src/sso214/components/Heading/Heading.test.tsx
  src/sso214/components/Heading/Heading.tsx
  src/sso214/components/List/List.test.tsx
  src/sso214/components/List/List.tsx
  src/sso214/components/Menu/Menu.test.tsx
  src/sso214/components/Menu/Menu.tsx
  src/sso214/components/Menu/types.ts
  src/sso214/components/MenuList/MenuList.test.tsx
  src/sso214/components/MenuList/MenuList.tsx
  src/sso214/data/MENU_LIST.ts
Labels: size/L

#25 [4주차] 정수현
  src/sasha1107/__tests__/MenuOption.test.tsx
  src/sasha1107/components/MenuOption.tsx
  src/sasha1107/components/index.ts
Labels: size/L
